// <auto-generated />
namespace RecipeShare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class logging1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logging1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505090049291_logging1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
