// <auto-generated />
namespace RecipeShare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class LotsOStuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LotsOStuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201505071851041_LotsOStuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
